name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      # Inject secrets into workflow environment
      - name: Set environment variables from GitHub Secrets
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          DB_PATH: ${{ secrets.DB_PATH }}
        run: |
          echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> $GITHUB_ENV
          echo "DB_PATH=${DB_PATH}" >> $GITHUB_ENV

      # Debug secrets
      - name: Debug secrets
        run: |
          echo "GOOGLE_CLIENT_ID is set? ${GOOGLE_CLIENT_ID:+YES}"
          echo "GOOGLE_CLIENT_SECRET is set? ${GOOGLE_CLIENT_SECRET:+YES}"
          echo "DB_PATH is set? ${DB_PATH:+YES}"

      - name: Run app
        run: npm start
